logging:
  level:
    root: info
    com.my.spring_batch: debug

spring:
  batch:
    job:
      names: ${job.name:NONE}
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mariadb://127.0.0.1:3307/spring_batch?serverTimezone=Asia/Seoul
    username: root
    password: password

